package csc1035.project3;

import javax.persistence.*;

@Entity
@Table(name = "Customers")
public class Customers {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "cid", updatable = false, nullable = false)
    private int cid; // Generated by Hibernate
    @Column(name = "surname")
    private String surname;
    @Column(name = "email")
    private String email;
    @Column(name = "phoneExt")
    private String phoneExt;

    public Customers(){

    }

    /** Constructor for Customers class.
     *
     * @param surname - Customer surname
     * @param email - Customer email
     * @param phoneExt - Customer phone extension
     */
    public Customers(String surname, String email, String phoneExt) {
        this.surname = surname;
        this.email = email;
        this.phoneExt = phoneExt;
    }

    /**
     * Customer Surname Getter
     * @return - Customer surname
     */
    public String getSurname() {
        return this.surname;
    }

    /**
     * Customer Surname Setter
     * @param surname -new Customer surname
     */
    public void setSurname(String surname) {
        this.surname = surname;
    }

    /**
     * Customer Email Getter
     * @return - Customer email
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Customer Email setter
     * @param email - new Customer email
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Customer phoneExt getter
     * @return - Customer phoneExt
     */
    public String getPhoneExt() {
        return this.phoneExt;
    }

    /**
     *  Customer phoneExt setter
     * @param phoneExt - new Customer phoneExt
     */
    public void setPhoneExt(String phoneExt) {
        this.phoneExt = phoneExt;
    }

    /**
     * Customer toString implementation
     * @return - A string representation of the Customer - their Surname, Email and phoneExt.
     */
    @Override
    public String toString(){
        return String.format("Surname: %s, Email: %s, phoneExt: %s", getSurname(), getEmail(), getPhoneExt());
    }
}
